language: rust

rust:
  - 1.19.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1
    - FEATURES="build-script-lib-rustfmt"

script:
  - pwd
  - ls -la
  - cargo test --verbose --all --features "${FEATURES}"
  - cargo build --verbose --all --examples --features "${FEATURES}"
