language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=build_script_build=debug

script:
  - pwd
  - ls -la
  - cargo test -vv --all
  - cargo build -vv --all --examples
